src/features/signup/SignUpForm.js, src/features/signup/TextField.js
https://www.loom.com/share/7d7a98184bdb4388bcfadb69132495e6
https://alkemy-labs.atlassian.net/browse/OT123-263
=> OT123-263/Sign-up-form

.eslintrc.js, package.json, src/features/signup/SignUpForm.js, src/features/signup/TextField.js
eslint config for the project, has to be used with "npm audit fix --force"
=> eslint fixes

src/themes/index.js
there's no ticket for this branch, just the global colorscheme.
=> added colors

src/features/contact/ContactForm.js, src/features/contact/TextField.js, src/pages/contact/ButtonInfo.jsx, src/pages/contact/ContactPage.css, src/pages/contact/ContactPage.jsx, src/pages/contact/IconInfo.jsx
Codigo optimizado y adaptado a la par de los demas formularios
=> Ot123 267/screen contact3

package-lock.json, package.json, src/components/testimonials/TestimonialForm.js, src/services/TestimonialsService.js, src/services/httpService.js
##DESCRIPTION
it implements the form for testimonials. it can add and update a testimonial. It still needs work on the input to upload images.
https://www.loom.com/share/2bc8925cb8b44c1c9e9b0ad01fd21677
https://alkemy-labs.atlassian.net/browse/OT123-323
=> OT123-323/testimonial-form

src/pages/backoffice/users/ListUsers.jsx
https://alkemy-labs.atlassian.net/browse/OT123-291
=> OT123-291 back office user list

src/components/news/NewsForm.js, src/services/NewsService.js
##DESCRIPTION
It works just like the testimonial form but with a few tweaks.
https://alkemy-labs.atlassian.net/browse/OT123-294
=> Ot123-294/news-form

src/components/navbar/Header.jsx, src/components/navbar/Sidebar.jsx
There is a still a bug in the sidebar that needs to be fix. Nothing renders when the sidebar is clicked
EDIT: Now all works as intended
https://alkemy-labs.atlassian.net/browse/OT123-279
=> OT123-279/Link-navbar-screens

package-lock.json, package.json, src/components/Spinner.js
https://alkemy-labs.atlassian.net/browse/OT123-259
=> OT123-259/Spinner

src/app/slices/auth.js, src/app/store.js, src/hooks/useUser.js
https://alkemy-labs.atlassian.net/browse/OT123-283
https://alkemy-labs.atlassian.net/browse/OT123-310
=> OT123-283/adds reducers and actions for the user

src/components/news/Card.jsx, src/components/news/News.jsx
https://alkemy-labs.atlassian.net/browse/OT123-287
https://loom.com/share/f15f629974064d72aec26fef5ad38f72
=> OT123-287 added news screen

src/components/news/Card.jsx, src/components/news/Entry.jsx, src/components/news/News.jsx
https://alkemy-labs.atlassian.net/browse/OT123-289
=> OT123-289 screen news detail

src/pages/backoffice/news/ListNews.js, src/services/newsService.js
https://alkemy-labs.atlassian.net/browse/OT123-286
=> OT123-286/List-News

src/pages/backoffice/categories/ListCategories.js, src/router/index.js
##DESCRIPTION
The list of categories for the backoffice didn't exist so I created it. That way I was able to do this ticket
https://alkemy-labs.atlassian.net/browse/OT123-304
https://www.loom.com/share/6b155acd114343ec8572a6bc195f4d8e
=> OT123-304/List-categories-with-delete-handler

src/components/categories/CategoriesForm.js, src/services/categoriesService.js
https://alkemy-labs.atlassian.net/browse/OT123-340
=> OT123-340/categories-form

package-lock.json, package.json, src/components/activitiesForm/ActivitiesForm.js, src/components/activitiesForm/GridImages.jsx, src/services/imgUploadService.js
buffer installation and add buffer to imgUpload to solve uploading images to s3
=> Fix buffer react aws s3

src/components/Footer.jsx, src/services/httpService.js, src/services/organizationsService.js
https://alkemy-labs.atlassian.net/browse/OT123-320
=> OT123-320/Dynamic socials links to footer

src/hoc/AdminRoute.js, src/pages/notFound/NotFound.css, src/pages/notFound/NotFound.jsx
=> Ot123 371/check if the user of the state is an administrator

src/components/LogoutButton.jsx, src/components/menus/AdminMenu.js, src/components/navbar/Header.jsx, src/components/navbar/Sidebar.jsx
=> Ot123 369/logout action

src/components/alert/Alert.js, src/hooks/useUser.js, src/pages/profile/Profile.js
[OT-123-373](https://alkemy-labs.atlassian.net/browse/OT123-373)
Delete account functionality finished, this time works better.
Minor changes made in SERVER (branch OT-123-373-delete-account).
=> OT-123-373 | Delete account

src/features/contact/ContactForm.js, src/pages/contact/ContactPage.jsx
The organization data now its dynamic
=> OT123/Dynamic Contact Page

src/components/home/editWelcomeText.jsx, src/components/news/NewsForm.js, src/components/pageUtils/Card.jsx, src/components/pageUtils/Detail.jsx, src/pages/Home.jsx, src/pages/backoffice/testimonials/ListTestimonials.js, src/services/organizationsService.js
=> Add components in home page
